"""
Renderer template Flask ke HTML dengan context yang benar
FIXED: Compatible with actual template requirements
"""
from flask import Flask
from app import create_app
from bakery.config import BakeryConfig

class TemplateRenderer:
    """Render template Flask dalam mode bakery - FIXED"""
    
    def __init__(self):
        self.app = self.create_bakery_app()
    
    def create_bakery_app(self):
        """Buat Flask app khusus untuk bakery"""
        app = create_app()
        
        # Konfigurasi khusus bakery
        app.config.update({
            "SERVER_NAME": "abi-sumsel.my.id",  # Gunakan domain asli
            "APPLICATION_ROOT": "/",
            "PREFERRED_URL_SCHEME": "https",
            "BAKERY_MODE": True
        })
        
        return app
    
    def render_url(self, url, context_data=None):
        """Render URL tertentu ke HTML string - FIXED"""
        if context_data is None:
            context_data = {}
        
        # Debug info
        print(f"🎨 Rendering URL: {url}")
        
        with self.app.test_request_context(path=url):
            # Tentukan template berdasarkan URL atau context_data
            if url == "/search/":
                # Halaman search khusus
                template = "public/search.html"
                print(f"   Type: Search Page")
            elif "article" in context_data:
                # Detail artikel
                template = "public/info/article.html"
                print(f"   Type: Article Detail - {context_data['article'].get('title', 'Untitled')}")
            elif "articles" in context_data:
                # Daftar artikel
                template = "public/info/index.html"
                print(f"   Type: Article List - {len(context_data.get('articles', []))} articles")
            elif url == "/":
                # Homepage
                template = "public/home.html"
                print(f"   Type: Homepage")
            else:
                # Halaman regular
                template = "public/page.html"
                if "page" in context_data:
                    print(f"   Type: Page - {context_data['page'].get('title', 'Untitled')}")
                else:
                    print(f"   Type: Page (no data)")
            
            print(f"   Template: {template}")
            
            # Render template
            from flask import render_template
            try:
                html = render_template(template, **context_data)
                html = self.clean_head_spaces(html)
                print(f"   ✅ Successfully rendered")
                return html
            except Exception as e:
                print(f"   ❌ Template rendering error: {e}")
                import traceback
                traceback.print_exc()
                
                # Fallback: coba template alternatif
                try:
                    if template == "public/info/article.html":
                        # Coba fallback ke page.html untuk artikel
                        html = render_template("public/page.html", **context_data)
                        html = self.clean_head_spaces(html)
                        print(f"   ✅ Fallback to page.html successful")
                        return html
                    elif template == "public/search.html":
                        # Coba fallback ke page.html untuk search
                        html = render_template("public/page.html", **context_data)
                        print(f"   ✅ Fallback to page.html for search successful")
                        return html
                except Exception as e2:
                    print(f"   ❌ Fallback also failed: {e2}")
                
                # Ultimate fallback HTML minimal
                title = ""
                if "article" in context_data:
                    title = context_data["article"].get("title", "")
                elif "page" in context_data:
                    title = context_data["page"].get("title", "")
                
                return f"""<!DOCTYPE html>
    <html>
    <head>
        <title>{title}</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>{title}</h1>
        <p>Page generated by FlaskCMS Bakery</p>
        <p>Error during template rendering: {e}</p>
    </body>
    </html>"""
                
    def clean_head_spaces(self, html):
        """Bersihkan spasi berlebih di dalam tag head"""
        if not html:
            return html
        
        import re
        
        # Pattern untuk mencari konten di dalam <head>...</head>
        head_pattern = re.compile(r'(<head[^>]*>)(.*?)(</head>)', re.DOTALL | re.IGNORECASE)
        
        def clean_head(match):
            open_tag = match.group(1)
            head_content = match.group(2)
            close_tag = match.group(3)
            
            # Hapus semua newline dan spasi berlebih di awal dan akhir baris
            lines = head_content.split('\n\n')
            cleaned_lines = []
            
            for line in lines:
                # Hapus spasi di awal dan akhir baris
                line = line.strip()
                # Jika baris tidak kosong, tambahkan
                if line:
                    cleaned_lines.append(line)
            
            # Gabungkan dengan spasi tunggal
            cleaned_content = ' '.join(cleaned_lines)
            
            # Hapus spasi di sekitar tag
            cleaned_content = re.sub(r'>\s+<', '>\n<', cleaned_content)
            
            return f"{open_tag}{cleaned_content}{close_tag}"
        
        return head_pattern.sub(clean_head, html)            