"""
Renderer template Flask ke HTML dengan context yang benar
FIXED: Compatible with actual template requirements
"""
from flask import Flask
from app import create_app
from bakery.config import BakeryConfig

class TemplateRenderer:
    """Render template Flask dalam mode bakery - FIXED"""
    
    def __init__(self):
        self.app = self.create_bakery_app()
    
    def create_bakery_app(self):
        """Buat Flask app khusus untuk bakery"""
        app = create_app()
        
        # Konfigurasi khusus bakery
        app.config.update({
            "SERVER_NAME": "localhost",
            "APPLICATION_ROOT": "/",
            "PREFERRED_URL_SCHEME": "https",
            "BAKERY_MODE": True
        })
        
        return app
    
    def render_url(self, url, context_data=None):
        """Render URL tertentu ke HTML string - FIXED"""
        if context_data is None:
            context_data = {}
        
        # Debug info
        print(f"🎨 Rendering URL: {url}")
        
        with self.app.test_request_context(path=url):
            # Tentukan template berdasarkan context_data, bukan hanya URL
            if "article" in context_data:
                # Detail artikel
                template = "public/info/article.html"
                print(f"   Type: Article Detail - {context_data['article'].get('title', 'Untitled')}")
            elif "articles" in context_data:
                # Daftar artikel
                template = "public/info/index.html"
                print(f"   Type: Article List - {len(context_data.get('articles', []))} articles")
            elif url == "/":
                # Homepage
                template = "public/home.html"
                print(f"   Type: Homepage")
            else:
                # Halaman regular
                template = "public/page.html"
                if "page" in context_data:
                    print(f"   Type: Page - {context_data['page'].get('title', 'Untitled')}")
                else:
                    print(f"   Type: Page (no data)")
            
            print(f"   Template: {template}")
            
            # Render template
            from flask import render_template
            try:
                html = render_template(template, **context_data)
                print(f"   ✅ Successfully rendered")
                return html
            except Exception as e:
                print(f"   ❌ Template rendering error: {e}")
                import traceback
                traceback.print_exc()
                
                # Fallback: coba template alternatif
                try:
                    if template == "public/info/article.html":
                        # Coba fallback ke page.html untuk artikel
                        html = render_template("public/page.html", **context_data)
                        print(f"   ✅ Fallback to page.html successful")
                        return html
                except Exception as e2:
                    print(f"   ❌ Fallback also failed: {e2}")
                
                # Ultimate fallback HTML minimal
                title = ""
                if "article" in context_data:
                    title = context_data["article"].get("title", "")
                elif "page" in context_data:
                    title = context_data["page"].get("title", "")
                
                return f"""<!DOCTYPE html>
    <html>
    <head>
        <title>{title}</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>{title}</h1>
        <p>Page generated by FlaskCMS Bakery</p>
        <p>Error during template rendering: {e}</p>
    </body>
    </html>"""