"""
Renderer template Flask ke HTML dengan context yang benar
FIXED: Compatible with actual template requirements
"""
from flask import Flask
from app import create_app
from bakery.config import BakeryConfig

class TemplateRenderer:
    """Render template Flask dalam mode bakery - FIXED"""
    
    def __init__(self):
        self.app = self.create_bakery_app()
    
    def create_bakery_app(self):
        """Buat Flask app khusus untuk bakery"""
        app = create_app()
        
        # Konfigurasi khusus bakery
        app.config.update({
            "SERVER_NAME": "localhost",
            "APPLICATION_ROOT": "/",
            "PREFERRED_URL_SCHEME": "https",
            "BAKERY_MODE": True
        })
        
        return app
    
    def render_url(self, url, context_data=None):
        """Render URL tertentu ke HTML string - FIXED"""
        if context_data is None:
            context_data = {}
        
        # Debug info
        print(f"🎨 Rendering URL: {url}")
        if "article" in context_data:
            print(f"   Type: Article - {context_data['article'].get('title', 'Untitled')}")
        elif "page" in context_data:
            print(f"   Type: Page - {context_data['page'].get('title', 'Untitled')}")
        
        with self.app.test_request_context(path=url):
            # Determine which template to use
            if url == "/":
                template = "public/home.html"
            elif url.startswith("/info/") and "/" not in url[6:]:
                # Article detail
                template = "public/info/article.html"
            elif url == "/info/":
                # Article list
                template = "public/info/index.html"
            else:
                # Regular page
                template = "public/page.html"
            
            print(f"   Template: {template}")
            
            # Render template with proper context
            from flask import render_template
            try:
                html = render_template(template, **context_data)
                print(f"   ✅ Successfully rendered")
                return html
            except Exception as e:
                print(f"   ❌ Template rendering error: {e}")
                # Fallback minimal HTML
                title = ""
                if "article" in context_data:
                    title = context_data["article"].get("title", "")
                elif "page" in context_data:
                    title = context_data["page"].get("title", "")
                
                return f"""<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <meta charset="utf-8">
</head>
<body>
    <h1>{title}</h1>
    <p>Page generated by FlaskCMS Bakery</p>
    <p>Error during template rendering: {e}</p>
</body>
</html>"""